version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=development
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    networks:
      - dnd-network
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - dnd-network
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dnd-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - dnd-network
    depends_on:
      - backend
      - frontend
    profiles:
      - production

networks:
  dnd-network:
    driver: bridge

volumes:
  redis-data: