apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dnd-game-prod

bases:
  - ../../base

resources:
  - namespace.yaml
  - network-policy.yaml
  - monitoring.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: dnd-game-config
    behavior: merge
    literals:
      - ENV=production
      - DB_MAX_OPEN_CONNS=150
      - DB_MAX_IDLE_CONNS=50
      - REACT_APP_ENVIRONMENT=production

replicas:
  - name: backend
    count: 5
  - name: frontend
    count: 3

images:
  - name: dnd-backend
    newName: ghcr.io/your-org/dnd-backend
    newTag: v1.0.0 # Use specific version tags in production
  - name: dnd-frontend
    newName: ghcr.io/your-org/dnd-frontend
    newTag: v1.0.0

transformers:
  - labels.yaml