# Default values for dnd-game
# This is a YAML-formatted file

global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

backend:
  enabled: true
  replicaCount: 3
  
  image:
    registry: ghcr.io
    repository: your-org/dnd-backend
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  
  env:
    PORT: "8080"
    ENV: "production"
    DB_MAX_OPEN_CONNS: "100"
    DB_MAX_IDLE_CONNS: "25"
    DB_MAX_LIFETIME: "30m"
    ACCESS_TOKEN_DURATION: "15m"
    REFRESH_TOKEN_DURATION: "168h"
    BCRYPT_COST: "12"
    AI_PROVIDER: "openai"
    AI_MODEL: "gpt-4-turbo-preview"
  
  secrets:
    DB_PASSWORD: ""
    JWT_SECRET: ""
    AI_API_KEY: ""

frontend:
  enabled: true
  replicaCount: 2
  
  image:
    registry: ghcr.io
    repository: your-org/dnd-frontend
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  
  env:
    REACT_APP_API_URL: "https://api.dndgame.example.com"
    REACT_APP_WS_URL: "wss://api.dndgame.example.com"
    REACT_APP_ENVIRONMENT: "production"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  
  hosts:
    - host: dndgame.example.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: api.dndgame.example.com
      paths:
        - path: /
          pathType: Prefix
          service: backend
  
  tls:
    - secretName: dnd-game-tls
      hosts:
        - dndgame.example.com
        - api.dndgame.example.com

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    username: "dndgame"
    password: "changeme"
    database: "dndgame"
  
  primary:
    persistence:
      enabled: true
      size: 10Gi
    
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi

redis:
  enabled: true
  auth:
    enabled: true
    password: "changeme"
  
  master:
    persistence:
      enabled: true
      size: 2Gi
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

networkPolicy:
  enabled: true

podSecurityPolicy:
  enabled: false

serviceAccount:
  create: true
  automountServiceAccountToken: true
  annotations: {}

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /metrics

backup:
  enabled: false
  schedule: "0 2 * * *"
  retention: 7