# golangci-lint configuration
version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref  # use exportloopref for v2.1.6
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - godot
    - godox
    - goheader
    - nestif
    - revive

  disable:
    - depguard
    - funlen
    - gocognit
    - gomodguard
    - wsl
    - gochecknoglobals

linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/your-username/dnd-game
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return
        ignored-numbers:
          - '0'
          - '1'
          - '2'
          - '3'
          - '10'
        ignored-files:
          - 'test'
        ignored-functions:
          - 'strconv.ParseInt'
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  # Exclude directories from analysis
  exclude-dirs:
    - vendor
    - node_modules
  
  # Exclude files from analysis
  exclude-files:
    - ".*_mock.go"
    - ".*_gen.go"
  
  # Use default exclusions
  exclude-use-default: true
  
  # Custom exclusion rules
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - gosec
        - noctx
        - dogsled
        - bodyclose
    - path: testing\.go
      linters:
        - gosec
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals
    - path: internal/models/
      linters:
        - govet  # placeholder to keep the rule structure
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - stylecheck
      text: "ST1000:"
    - linters:
        - revive
      text: "exported:"

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false