# golangci-lint configuration
run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - godot
    - godox
    - goheader
    - nestif
    - revive
    - shadow  # Enable shadow linter instead of govet.check-shadowing

  disable:
    - depguard
    - funlen
    - gocognit
    - gomodguard
    - wsl
    - gochecknoglobals

linters-settings:
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/your-username/dnd-game
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '10'
    ignored-files:
      - 'test'
    ignored-functions:
      - 'strconv.ParseInt'
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    # allow-leading-space removed in v1.55+
    allow-unused: false
    require-explanation: false
    require-specific: false
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-dirs:
    - vendor
    - node_modules
  exclude-files:
    - ".*_mock.go"
    - ".*_gen.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - gosec
        - noctx
        - dogsled
        - bodyclose
    - path: testing\.go
      linters:
        - gosec
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals
    - path: internal/models/
      linters:
        - govet
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - stylecheck
      text: "ST1000:"
    - linters:
        - revive
      text: "exported:"
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false