apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnd-game-backend
  namespace: dnd-game
  labels:
    app.kubernetes.io/name: dnd-game
    app.kubernetes.io/component: backend
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnd-game-frontend
  namespace: dnd-game
  labels:
    app.kubernetes.io/name: dnd-game
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnd-game-postgres
  namespace: dnd-game
  labels:
    app.kubernetes.io/name: dnd-game
    app.kubernetes.io/component: database
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnd-game-redis
  namespace: dnd-game
  labels:
    app.kubernetes.io/name: dnd-game
    app.kubernetes.io/component: cache
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dnd-game-backend
  namespace: dnd-game
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dnd-game-backend
  namespace: dnd-game
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dnd-game-backend
subjects:
- kind: ServiceAccount
  name: dnd-game-backend
  namespace: dnd-game