apiVersion: v1
kind: Secret
metadata:
  name: dnd-game-secrets
  namespace: dnd-game
  labels:
    app.kubernetes.io/name: dnd-game
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials
  DB_PASSWORD: "CHANGE_ME_SECURE_PASSWORD"
  
  # Redis password
  REDIS_PASSWORD: "CHANGE_ME_REDIS_PASSWORD"
  
  # JWT secret (at least 32 characters)
  JWT_SECRET: "CHANGE_ME_SECURE_JWT_SECRET_MIN_32_CHARS"
  
  # AI API key
  AI_API_KEY: "CHANGE_ME_OPENAI_API_KEY"
  
  # Sentry DSN (optional)
  SENTRY_DSN: ""
  
  # Google Analytics (optional)
  GA_TRACKING_ID: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dnd-game
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: "dndgame"
  POSTGRES_PASSWORD: "CHANGE_ME_SECURE_DB_PASSWORD"
  POSTGRES_DB: "dndgame"

---
# Example of creating secrets from command line:
# kubectl create secret generic dnd-game-secrets \
#   --from-literal=DB_PASSWORD='your-secure-password' \
#   --from-literal=REDIS_PASSWORD='your-redis-password' \
#   --from-literal=JWT_SECRET='your-jwt-secret-min-32-chars' \
#   --from-literal=AI_API_KEY='your-openai-api-key' \
#   -n dnd-game