# Backend deployment patch for development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: backend
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "200Mi"
          limits:
            memory: "256Mi"
            cpu: "500m"
            ephemeral-storage: "500Mi"

---
# Frontend deployment patch for development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "200m"
            ephemeral-storage: "200Mi"

---
# Postgres StatefulSet patch for development
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: postgres
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "200Mi"
          limits:
            memory: "256Mi"
            cpu: "500m"
            ephemeral-storage: "500Mi"

---
# Redis deployment patch for development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "200m"
            ephemeral-storage: "200Mi"